### ISSUE TITLE
Minecraft to Discord = Works fine | Discord to Minecraft throwing error.

### ISSUE THREAD

**Issue by CyberSecGuy** [LXGaming/DiscordBot#10]
Error:
```
[21:01:19] [ReadingThread/WARN]: [21:01:19] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[21:01:19] [ReadingThread/WARN]: [21:01:19] [Fatal] [JDA]: Encountered an exception:
[21:01:19] [ReadingThread/WARN]: java.lang.NullPointerException
[21:01:19] [ReadingThread/WARN]:        at io.github.lxgaming.discordbot.listeners.MessageListener.onMessageReceived(MessageListener.java:42)
[21:01:19] [ReadingThread/WARN]:        at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:184)
[21:01:19] [ReadingThread/WARN]:        at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
[21:01:19] [ReadingThread/WARN]:        at net.dv8tion.jda.handle.MessageReceivedHandler.handleInternally(MessageReceivedHandler.java:79)
[21:01:19] [ReadingThread/WARN]:        at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:38)
[21:01:19] [ReadingThread/WARN]:        at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:611)
[21:01:19] [ReadingThread/WARN]:        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:325)
[21:01:19] [ReadingThread/WARN]:        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
[21:01:19] [ReadingThread/WARN]:        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:261)
[21:01:19] [ReadingThread/WARN]:        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:239)
[21:01:19] [ReadingThread/WARN]:        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:946)
[21:01:19] [ReadingThread/WARN]:        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:729)
[21:01:19] [ReadingThread/WARN]:        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:109)
[21:01:19] [ReadingThread/WARN]:        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:65)

```

Config File:
```
DiscordBot:
  Credentials:
    # Information on how to get a BotToken below
    # https://www.spigotmc.org/resources/discordbot-bungeecord-edition.19347/update?update=85962
    BotToken: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    # Must be your Discord Channel ID. (The Bot will automatically set this if left blank).
    Guild: '247171433279520768'
  TextChannels:
    # These Must be IDs From Discord
    # Leaving Bot Blank will cause the plugin to output all TextChannels and their IDs into Console
    Bot: '247171433279520768'
    InGame: '247171433279520768'
  Messages:
    # At the moment there is only EN, but you can modify the messages.yml how you want
    Locale: 'en'
    # Prefix is what invokes a command eg !help
    CommandPrefix: '?'
    # Discord Message and other information output to Console
    ConsoleOutput: true
    # Don't care if the Bot has Connected? Well now he doesn't have to tell you
    ConnectionMessage: true
    # NOTE: In the messages.yml setting messages to 'null' will allow you to stop specific events sending messages
    # Should Messages be sent to Minecraft/Discord?
    SendInGame: true
    SendDiscord: true
    # Set this to true if you want global chat messages to be sent to discord regardless of other chat plugins
    ForceChat: false
  Listeners:
    # Turns on all the Event Listeners, Good if you have 2 Bots running. Wouldn't want double spam would we?
    MainBot: true
    # Discord Events
    # When a user changes there Avatar/Game/Name or they become Online/Away/Offline/Deafened/Muted should we tell the world?
    UserAvatarUpdate: false
    UserGameUpdate: false
    UserNameUpdate: false
    UserOnlineStatusUpdate: true
    VoiceServerDeaf: true
    VoiceServerMute: true
  Events:
    # Minecraft Events
    # Enable/Disable Chat/Join/Quit/Death Messages
    PlayerChat: true
    PlayerJoin: true
    PlayerQuit: true
    PlayerDeath: true
```

**Comment by CyberSecGuy** [comment]
Chat Plugin:  EssentialsChat

**Comment by CyberSecGuy** [comment]
**FIXED**

```
    # Must be your Discord Channel ID. (The Bot will automatically set this if left blank).
    Guild: '247171433279520768'
```

I set the Guild to blank, and it now picks up Discord **-->** Minecraft

```
    # Must be your Discord Channel ID. (The Bot will automatically set this if left blank).
    Guild: ''
```
